### PR TITLE
using libvirt for renaming domains

### PR DESCRIPTION
**Pull request by coreyberla**
this is the resolution for issue #204 per the discussion in the issue

### CODE REVIEW

**Comment by crobinso** [comment]
Thanks for the patches, but this is not acceptable as is. That function you are altering is used by storage pools and network objects as well, but you are replacing it with a virDomain specific API. Any domain specific changes should be in domain.py:vmmDomain:rename_domain function.

* Patches should have descriptive commit messages
* Squash fixup patches together with `git rebase -i`
* No unnecessary whitespace changes

I'm curious, is there some behavior of the rename API that you want specifically which virt-manager isn't handling?

**Comment by coreyberla** [comment]
I made the change to resolve the issue in #204 where renaming would lose settings (specifically boot on start). I was able to replicate the issue and resolved it by taking your suggestion on the issue. It was an oversight on my part about the storage and network components. I'll fix and make sure to do so appropriately!

**Comment by crobinso** [comment]
Ah indeed I should have looked at #204 to remind myself.

Switching to use domain rename is one solution but it's also more complicated:
* We can only use it for libvirt drivers that support it.
* We need to keep the old code around for drivers that don't support it.
* We need to make sure we test both code paths in tests/uitests which will take a bit of work

It's a useful thing to do but it's kinda involved. The alternative for #204 is to just implement that specific change in our rename implementation. That's probably as simple as adding

```
oldautostart = self.get_autostart()
# do the rename
self.set_autostart(oldautostart)
```

In libvirtobject.py. That also has the benefit of fixing it for our network and pool rename implementations as well

**Comment by coreyberla** [comment]
Many apologies for the mess of commits (it's been a while since I used git).  I tested your suggestion and it worked, so I added the code.  I also added a check to see if the name actually changed (if the user entered text but ultimately left the name the same, it'd throw an error)

**Comment by crobinso** [comment]
Thanks, I split up your change, tweaked the commit messages, and pushed.

**Pull request closed without merging**
