### PR TITLE
add loongarch support

### PR DESCRIPTION
**Pull request by Venland**
add loongarch support

### CODE REVIEW

**Comment by weigang-li** [comment]
ping

**Comment by wanywhn** [comment]
ping

**Comment by crobinso** [comment]
Sorry for lack of response. Just looking at the diff I can see there is no test suite coverage, which is a requirement for a case like this.

* Take real `virsh capabilities` output and put it in `tests/data/kvm-loongarch64.xml`
* Take real `virsh domcapabilities` output and put it in `tests/data/kvm-loongarch64-domcaps.xml`
* In `tests/utils.py` add something like `self.kvm_loongarch64 = _uri_qemu + _caps("kvm-loongarch64.xml") + _domcaps("kvm-loongarch64.xml")
* Then add a test case in `tests/test_cli.py` that uses that mock connection. Something like this

```diff
diff --git a/tests/test_cli.py b/tests/test_cli.py
index b2f707b9..cc4543f9 100644
--- a/tests/test_cli.py
+++ b/tests/test_cli.py
@@ -1197,6 +1197,13 @@ c.add_compare("--connect %(URI-KVM-AARCH64)s --osinfo fedora30 --arch aarch64 --
 c.add_compare("--connect %(URI-KVM-AARCH64)s --disk %(EXISTIMG1)s --os-variant fedora28 --cloud-init", "aarch64-cloud-init")
 
 
+#####################
+# loongarch64 tests #
+#####################
+
+c.add_compare("--osinfo fedora19 --nodisks --pxe --connect " + utils.URIs.kvm_loongarch64, "kvm-loongarch64-basic")
+
+
 
 #################
 # AMD sev tests #
```

* Run `pytest`. Commit the generated XML output to git if it succeeds.


That should be the first commit. In following commits when you change virtinst logic, `pytest --regenerate-output` should also show the generated XML change with it. Commit those changes alongside your code changes.

**Pull request closed without merging**
