### PR TITLE
virt-install: fix --clouduser-ssh-key

### PR DESCRIPTION
**Pull request by ncopa**
Fix the cloud-init config file for --clouduser-ssh key.

Fixes commit 22478f307dd9 (virt-install: Add --cloud-init clouduser-ssh-key=)

Resolves: https://github.com/virt-manager/virt-manager/issues/452

### CODE REVIEW

**Comment by phrdina** [comment]
Hi, thanks for posting this patch. Unfortunately it doesn't work as there are multiple issue.

The correct attribute is `ssh_authorized_keys` because the old attribute `ssh-authorized-keys` was deprecated and works only if used for specific user. For the default user only `ssh_authorized_keys` works.

The second issue is more complex and will happen only if both root and coulduser keys are specified. If that happens the following config is created:
```yaml
users:
  - name: root
    ssh_authorized_keys:
      - rsa-ssh ......
ssh_authorized_keys:
  - rsa-ssh ......
```
which makes the default user removed.

The correct configuration needs to be like this:
```yaml
users:
  - default
  - name: root
    ssh_authorized_keys:
      - rsa-ssh ......
ssh_authorized_keys:
  - rsa-ssh ......
```
to have the default user created as well.

**Comment by ncopa** [comment]
Thanks for reviewing it. Both issues have been addressed.

**Comment by ncopa** [comment]
Should we add the `- default` if only root ssh key is set, or should setting root ssh key delete the clouduser (eg exclude the `- default`)?

**Comment by phrdina** [comment]
I would say we should keep the default user to have consistent behavior. Before this patch it was inconsistent:
```
  root-password-file     =>     default user created
  root-ssh-key           =>     default user missing
  clouduser-ssh-key      =>     default user created
  both ssh keys          =>     default user missing
```
after this change default user will be created all the time.

Users can specify `user-data` and provide more details they want to do with the VM including any user configuration. The options above are just a shortcuts to the basic configuration in order to be able to ssh/log into the VM.

**Comment by phrdina** [comment]
Btw: you can run `pytest --regenerate-output` to help you with fixing tests, review the changes it does and if it's ok commit it. That should help you make the test here working again.

**Pull request merged**
